// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opgqrdltnngkhjymgmmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZ3FyZGx0bm5na2hqeW1nbW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDY2ODcsImV4cCI6MjA1OTIyMjY4N30.K9p-IjOiYbSDBHlSLuhc7Uy1HQrReec8796x1O2FnlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);